### ISSUE TITLE
samples doesn't accept parameters

### ISSUE THREAD

**Issue by lomnes-atlast-food** [rsnodgrass/pysensorpush#2]
Thanks for pulling this together!  I've been using it and have found it super helpful!

One thing I noticed in my implementation is that when I call:

`sensorpush = PySensorPush(username, password)
sensorpush.samples`
I get the most recent samples from various sensors, but I cannot pass the parameters to this because it is defined with the @property decorator.

E.g.
`sensorpush.samples(limit=10)`
returns an error

Would an improvement be to remove the @property decorator?  This would mean that users would have to call samples as a method like:

`sensorpush.samples()`

**Comment by dairiki** [comment]
This appears to have been fixed in 846b7cb99d799c434c7cf77eba3fed071371d1c7
