### ISSUE TITLE
Module on Pypi appears broken

### ISSUE THREAD

**Issue by alsparks** [rsnodgrass/pysensorpush#5]
I used pip to install pysensorpush on my system, and it appears to report version 0.1.6.  If I download the source from here, and pip install, the module appears to work ok.

However, the version on Pypi, although claiming to be also 0.1.6 does not work because the samples method is still marked as @property.  

Downloading and unpacking the WHL file pysensorpush-0.1.6-py3-none-any.whl from: https://pypi.org/project/pysensorpush/#files and inspecting, shows the @property still in place.

Can you fix the PyPi entry so pip downloads the proper source?

**Comment by rsnodgrass** [comment]
Bumped version to 0.1.7 and released to PyPi
